# 1. Node.js LTS 이미지 사용
FROM node:18 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY src ./src
COPY public ./public
COPY vite.config.js ./
COPY index.html ./


RUN npm run build

FROM node:18

COPY --from=builder /app/dist ./dist

COPY package.json package-lock.json ./
RUN npm install

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--port", "5173", "--host", "0.0.0.0"]
