# 1. Node.js 버전을 20으로 업그레이드
FROM node:20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY src ./src
COPY public ./public
COPY vite.config.js ./
COPY index.html ./


RUN npm run build

FROM node:20

COPY --from=builder /app/dist ./dist

COPY package.json package-lock.json ./
RUN npm install

EXPOSE 5173

# serve 설치 및 실행 (타임아웃 증가)
RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "5173", "--no-request-logging", "--timeout", "3600000"]
